version: "3.9"

services: 
  api: 
    container_name: chat-api 
    build:
      context: ../flask_messenger/api 
    ports:
      - 8000:8001
    environment: 
      - APP_SETTINGS=project.config 
      - DATABASE_URL=postgres://postgres:postgres@messenger-db:5432/messages_dev 
      - DATABASE_TEST_URL=postgres://postgres@messenger-db:5432/messages_test 
      - SECRET_KEY=precious_key

    depends_on: 
      messenger-db: 
        condition: service_healthy
    links: 
        - messenger-db


  messenger-db: 
    container_name: messenger-db 
    build:
      context: ../flask_messenger/db 
    ports:
      - 5435:5432 
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    healthcheck:
      test: exit 0

  nginx: 
    container_name: nginx 
    build: ./nginx/ 
    restart: always 
    ports: 
      - 80:80
    depends_on: 
      api: 
        condition: service_started 
      chat_server: 
        condition: service_started
      links:
        - api 
        - chat_server

  chat_server:
    container_name: chat_server 
    build: 
      context: ../flask_messenger/chat_server 
    ports: 
      - '8082:8082' 
    environment: 
      - APP_SETTINGS=project.config 
    depends_on: 
      api: 
        condition: service_healthy 
      messenger-db: 
        condition: service_healthy
